In [91]:
import pandas as pd
# import numpy as np
from numpy import log as ln
df = pd.DataFrame(columns = ['version', 'dry1', 'glow1', 'reserve', 'dry2', 'glow2', 'payload', 'isp1', 'isp2', 'thrust1', 'thrust2'])
df = df.append(pd.DataFrame([['NG_120_45_ton_cargo', 110.0, 1100.0, 50, 12.0, 120, 45.0, 320.0, 440.0, 1900, 120 ]], columns=df.columns)
).append(pd.DataFrame([['NG_120_30_ton_cargo', 110, 1100, 50, 12, 120, 30, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_120_13_ton_cargo', 110, 1100, 50, 12, 120, 13, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_120_7_ton_cargo', 110, 1100, 50, 12, 120, 7, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_120_20_ton_cargo', 110, 1100, 100, 12, 120, 20, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_120_13_ton_cargo', 110, 1100, 100, 12, 120, 13, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_120_7_ton_cargo', 110, 1100, 100, 12, 120, 7, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_200_45_ton_cargo', 110, 1100, 50, 16, 200, 45, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_200_20_ton_cargo', 110, 1100, 50, 16, 200, 20, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_200_13_ton_cargo', 110, 1100, 50, 16, 200, 13, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_200_7_ton_cargo', 110, 1100, 50, 16, 200, 7, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_200_45_ton_cargo', 110, 1100, 100, 16, 200, 45, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_200_40_ton_cargo', 110, 1100, 100, 16, 200, 40, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_200_13_ton_cargo', 110, 1100, 100, 16, 200, 13, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['NG_200_7_ton_cargo', 110, 1100, 100, 16, 200, 7, 320, 440, 1900, 120]], columns=df.columns)
).append(pd.DataFrame([['Falcon_9_block5_GTO_reuse', 27.2, 455, 45, 4.5, 125, 5.5, 300, 348, 810, 95]], columns=df.columns)
).append(pd.DataFrame([['Falcon_9_block5_fairing_limit', 27.2, 455, 45, 4.5, 125, 10.886, 300, 348, 810, 95]], columns=df.columns)
).append(pd.DataFrame([['Falcon_9_block5_fuller_splash', 27.2, 455, 0, 4.5, 125, 22.8, 300, 348, 810, 95]], columns=df.columns))

df['fuel1'] = (df.glow1 - df.dry1 - df.reserve)
df['fuel2'] = (df.glow2 - df.dry2 - df.payload)
df['seperation'] = (df.dry1 + df.reserve + df.glow2)
df['burnout'] = (df.dry2+df.payload).astype(float)
df['delta1'] = 9.81 * df.isp1 * ln( (df.glow1+df.glow2).astype(float) / (df.seperation).astype(float))
# velocity * ln (m0/m1)
df['delta2'] = 9.81 * df.isp2 * ln((df.glow2.astype(float) / df.burnout.astype(float)))
df['delta_total'] = df.delta1+df.delta2
# df['burn1'] = df.fuel1/(df.thrust1/df.isp1/9.8)
# df['burn2'] = df.fuel2/(df.thrust2/df.isp2/9.8)
df.head(20)

,version,dry1,glow1,reserve,dry2,glow2,payload,isp1,isp2,thrust1,thrust2,fuel1,fuel2,seperation,burnout,delta1,delta2,delta_total
0,NG_120_45_ton_cargo,110.0,1100.0,50,12.0,120,45.000,320.0,440.0,1900,120,940,63,280,57.000,4620.326465,3213.302866,7833.629331
0,NG_120_30_ton_cargo,110.0,1100.0,50,12.0,120,30.000,320.0,440.0,1900,120,940,78,280,42.000,4620.326465,4531.452218,9151.778683
0,NG_120_13_ton_cargo,110.0,1100.0,50,12.0,120,13.000,320.0,440.0,1900,120,940,95,280,25.000,4620.326465,6770.773748,11391.100213
0,NG_120_7_ton_cargo,110.0,1100.0,50,12.0,120,7.000,320.0,440.0,1900,120,940,101,280,19.000,4620.326465,7955.352949,12575.679414
0,NG_120_20_ton_cargo,110.0,1100.0,100,12.0,120,20.000,320.0,440.0,1900,120,890,88,330,32.000,4104.546327,5705.226908,9809.773234
0,NG_120_13_ton_cargo,110.0,1100.0,100,12.0,120,13.000,320.0,440.0,1900,120,890,95,330,25.000,4104.546327,6770.773748,10875.320075
0,NG_120_7_ton_cargo,110.0,1100.0,100,12.0,120,7.000,320.0,440.0,1900,120,890,101,330,19.000,4104.546327,7955.352949,12059.899276
0,NG_200_45_ton_cargo,110.0,1100.0,50,16.0,200,45.000,320.0,440.0,1900,120,940,139,360,61.000,4030.781495,5125.481134,9156.262629
0,NG_200_20_ton_cargo,110.0,1100.0,50,16.0,200,20.000,320.0,440.0,1900,120,940,164,360,36.000,4030.781495,7401.755935,11432.537430
0,NG_200_13_ton_cargo,110.0,1100.0,50,16.0,200,13.000,320.0,440.0,1900,120,940,171,360,29.000,4030.781495,8335.061360,12365.842856
0,NG_200_7_ton_cargo,110.0,1100.0,50,16.0,200,7.000,320.0,440.0,1900,120,940,177,360,23.000,4030.781495,9335.609847,13366.391343
0,NG_200_45_ton_cargo,110.0,1100.0,100,16.0,200,45.000,320.0,440.0,1900,120,890,139,410,61.000,3622.518715,5125.481134,8747.999849
0,NG_200_40_ton_cargo,110.0,1100.0,100,16.0,200,40.000,320.0,440.0,1900,120,890,144,410,56.000,3622.518715,5494.629043,9117.147758
0,NG_200_13_ton_cargo,110.0,1100.0,100,16.0,200,13.000,320.0,440.0,1900,120,890,171,410,29.000,3622.518715,8335.061360,11957.580075
0,NG_200_7_ton_cargo,110.0,1100.0,100,16.0,200,7.000,320.0,440.0,1900,120,890,177,410,23.000,3622.518715,9335.609847,12958.128562
0,Falcon_9_block5_GTO_reuse,27.2,455.0,45,4.5,125,5.500,300.0,348.0,810,95,382.8,115,197.2,10.000,3174.936833,8622.534504,11797.471338
0,Falcon_9_block5_fairing_limit,27.2,455.0,45,4.5,125,10.886,300.0,348.0,810,95,382.8,109.614,197.2,15.386,3174.936833,7151.586087,10326.522921
0,Falcon_9_block5_fuller_splash,27.2,455.0,0,4.5,125,22.800,300.0,348.0,810,95,427.8,97.7,152.2,27.300,3937.241513,5193.969327,9131.210839